### ISSUE TITLE
The FRET format has changed, and Ogma supports the prior file format

### ISSUE THREAD

**Issue by EliasH-NMBU** [nasa/ogma#125]
Past: [FSMSpec.json](https://github.com/nasa/ogma/files/14176671/FSMSpec.json)

Present: [FRETDemo.json](https://github.com/nasa/ogma/files/14176672/FRETDemo.json)

**Comment by anmavrid** [comment]
Hi @EliasH-NMBU, 

Thanks for your interest in FRET and Ogma!

_**The FRET format for Ogma has not changed.**_

I see that you posted two files. These are not the same.

- The first JSON file is the [component specification ](https://github.com/NASA-SW-VnV/fret/blob/master/fret-electron/docs/_media/ExportingForAnalysis/analysis.md) that FRET generates for Ogma through the analysis portal.

- The second file is what FRET exports through the [Requirement Export button](https://github.com/NASA-SW-VnV/fret/blob/master/fret-electron/docs/_media/user-interface/exportImport/export.md). 

Anastasia
